{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d52faa92",
   "metadata": {},
   "outputs": [],
   "source": [
    "##for TXLA\n",
    "\n",
    "from satpy import Scene, find_files_and_readers\n",
    "from pyresample import create_area_def\n",
    "from satpy.writers import get_enhanced_image\n",
    "from datetime import datetime\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from glob import glob\n",
    "from satpy import MultiScene\n",
    "\n",
    "def MODIS(monthyear):\n",
    "    \n",
    "    i=0\n",
    "    base = '/home/hboi-ouri/Projects/RS_Files/MODIS2010-2012/' + monthyear + '/AQUA_MODIS.'\n",
    "\n",
    "    #files to be used\n",
    "    filenames = glob('/home/hboi-ouri/Projects/RS_Files/MODIS2010-2012/' + monthyear + '/AQUA_MODIS.*')\n",
    "    swats = np.unique([f.split('.')[1] for f in filenames])\n",
    "    \n",
    "    #area in the figure\n",
    "    extent = [-94, 27.5, -88, 30.5]\n",
    "    my_area = create_area_def('my_area', {'proj': 'lcc', 'lon_0': -91., 'lat_0': 29.5, 'lat_1': 29.5, 'lat_2': 29.5},\n",
    "                width=1500, height=750,\n",
    "                area_extent=extent, units='degrees')    \n",
    "        \n",
    "    fig =  plt.figure(figsize=(6, 4), dpi=400)\n",
    "\n",
    "    #loop\n",
    "    for swat in swats:\n",
    "        dayfiles = glob(base+swat+'*')\n",
    "        scn = Scene(dayfiles, reader='modis_l1b')\n",
    "        scn.load(['true_color'])\n",
    "\n",
    "        #reproject\n",
    "        new_scn = scn.resample(my_area)\n",
    "\n",
    "        #generate RGB from true color\n",
    "        rgb = get_enhanced_image(new_scn['true_color'])\n",
    "\n",
    "        #extract projection and lon lat from products\n",
    "        crs = new_scn['true_color'].attrs['area'].to_cartopy_crs()\n",
    "        lons, lats = new_scn['true_color'].attrs['area'].get_lonlats()\n",
    "\n",
    "        #true color\n",
    "        ax1 = plt.subplot(projection=crs)\n",
    "        rgb.data.plot.imshow(rgb='bands', transform=crs, ax=ax1)\n",
    "        \n",
    "        #title & save\n",
    "        ax1.set_title('MODISA_Mdelta_%s' % new_scn.start_time.isoformat())\n",
    "        fig.savefig('/home/hboi-ouri/Projects/NASA_Project/outputs/DailyImages/TXLA/MODISA_Mdelta_%s_rgb.png' % new_scn.start_time.isoformat())\n",
    "        fig.clear()\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "e78ea942",
   "metadata": {},
   "outputs": [],
   "source": [
    "##for TXLA\n",
    "\n",
    "from satpy import Scene, find_files_and_readers\n",
    "from pyresample import create_area_def\n",
    "from satpy.writers import get_enhanced_image\n",
    "from datetime import datetime\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from glob import glob\n",
    "from satpy import MultiScene\n",
    "\n",
    "def MODIS(monthyear):\n",
    "    \n",
    "    i=0\n",
    "    base = '/home/hboi-ouri/Projects/RS_Files/MODIS2010-2012/' + monthyear + '/AQUA_MODIS.'\n",
    "\n",
    "    #files to be used\n",
    "    filenames = glob('/home/hboi-ouri/Projects/RS_Files/MODIS2010-2012/' + monthyear + '/AQUA_MODIS.*')\n",
    "    swats = np.unique([f.split('.')[1] for f in filenames])\n",
    "    \n",
    "    #area in the figure\n",
    "    extent = [-94, 27.5, -88, 30.5]\n",
    "    my_area = create_area_def('my_area', {'proj': 'lcc', 'lon_0': -91., 'lat_0': 29.5, 'lat_1': 29.5, 'lat_2': 29.5},\n",
    "                width=1500, height=750,\n",
    "                area_extent=extent, units='degrees')    \n",
    "        \n",
    "    fig =  plt.figure(figsize=(6, 4), dpi=400)\n",
    "\n",
    "    #loop\n",
    "    for swat in swats:\n",
    "        dayfiles = glob(base+swat+'*')\n",
    "        scn = Scene(dayfiles, reader='modis_l1b')\n",
    "        scn.keys()\n",
    "        scn.available_dataset_names()\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "2df36a89",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "No filenames found for reader: modis_l1b\n",
      "Don't know how to open the following files: {'/home/hboi-ouri/Projects/RS_Files/MODIS2010-2012/SEP2012/AQUA_MODIS.20120901T191501.L2.OC.x.nc'}\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "No supported files found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Input \u001b[0;32mIn [6]\u001b[0m, in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43mMODIS\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mSEP2012\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "Input \u001b[0;32mIn [4]\u001b[0m, in \u001b[0;36mMODIS\u001b[0;34m(monthyear)\u001b[0m\n\u001b[1;32m     30\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m swat \u001b[38;5;129;01min\u001b[39;00m swats:\n\u001b[1;32m     31\u001b[0m     dayfiles \u001b[38;5;241m=\u001b[39m glob(base\u001b[38;5;241m+\u001b[39mswat\u001b[38;5;241m+\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m*\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m---> 32\u001b[0m     scn \u001b[38;5;241m=\u001b[39m \u001b[43mScene\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdayfiles\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mreader\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mmodis_l1b\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[1;32m     33\u001b[0m     scn\u001b[38;5;241m.\u001b[39mkeys()\n\u001b[1;32m     34\u001b[0m     scn\u001b[38;5;241m.\u001b[39mavailable_dataset_names()\n",
      "File \u001b[0;32m~/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/scene.py:133\u001b[0m, in \u001b[0;36mScene.__init__\u001b[0;34m(self, filenames, reader, filter_parameters, reader_kwargs)\u001b[0m\n\u001b[1;32m    130\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m filenames:\n\u001b[1;32m    131\u001b[0m     filenames \u001b[38;5;241m=\u001b[39m convert_remote_files_to_fsspec(filenames, storage_options)\n\u001b[0;32m--> 133\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_readers \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_create_reader_instances\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfilenames\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mfilenames\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    134\u001b[0m \u001b[43m                                              \u001b[49m\u001b[43mreader\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mreader\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    135\u001b[0m \u001b[43m                                              \u001b[49m\u001b[43mreader_kwargs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcleaned_reader_kwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    136\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_datasets \u001b[38;5;241m=\u001b[39m DatasetDict()\n\u001b[1;32m    137\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_wishlist \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mset\u001b[39m()\n",
      "File \u001b[0;32m~/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/scene.py:154\u001b[0m, in \u001b[0;36mScene._create_reader_instances\u001b[0;34m(self, filenames, reader, reader_kwargs)\u001b[0m\n\u001b[1;32m    149\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_create_reader_instances\u001b[39m(\u001b[38;5;28mself\u001b[39m,\n\u001b[1;32m    150\u001b[0m                              filenames\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[1;32m    151\u001b[0m                              reader\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[1;32m    152\u001b[0m                              reader_kwargs\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m):\n\u001b[1;32m    153\u001b[0m     \u001b[38;5;124;03m\"\"\"Find readers and return their instances.\"\"\"\u001b[39;00m\n\u001b[0;32m--> 154\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mload_readers\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfilenames\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mfilenames\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    155\u001b[0m \u001b[43m                        \u001b[49m\u001b[43mreader\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mreader\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    156\u001b[0m \u001b[43m                        \u001b[49m\u001b[43mreader_kwargs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mreader_kwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/readers/__init__.py:581\u001b[0m, in \u001b[0;36mload_readers\u001b[0;34m(filenames, reader, reader_kwargs)\u001b[0m\n\u001b[1;32m    578\u001b[0m         \u001b[38;5;28;01mbreak\u001b[39;00m\n\u001b[1;32m    580\u001b[0m _check_remaining_files(remaining_filenames)\n\u001b[0;32m--> 581\u001b[0m \u001b[43m_check_reader_instances\u001b[49m\u001b[43m(\u001b[49m\u001b[43mreader_instances\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    582\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m reader_instances\n",
      "File \u001b[0;32m~/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/readers/__init__.py:620\u001b[0m, in \u001b[0;36m_check_reader_instances\u001b[0;34m(reader_instances)\u001b[0m\n\u001b[1;32m    618\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_check_reader_instances\u001b[39m(reader_instances):\n\u001b[1;32m    619\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m reader_instances:\n\u001b[0;32m--> 620\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mNo supported files found\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m    621\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28many\u001b[39m(\u001b[38;5;28mlist\u001b[39m(r\u001b[38;5;241m.\u001b[39mavailable_dataset_ids) \u001b[38;5;28;01mfor\u001b[39;00m r \u001b[38;5;129;01min\u001b[39;00m reader_instances\u001b[38;5;241m.\u001b[39mvalues()):\n\u001b[1;32m    622\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mNo dataset could be loaded. Either missing \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    623\u001b[0m                          \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mrequirements (such as Epilog, Prolog) or none of the \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    624\u001b[0m                          \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mprovided files match the filter parameters.\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[0;31mValueError\u001b[0m: No supported files found"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<Figure size 2400x1600 with 0 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "MODIS('SEP2012')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fbf88c09",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "5f24dbad",
   "metadata": {},
   "outputs": [],
   "source": [
    "## For FLBay\n",
    "\n",
    "from satpy import Scene, find_files_and_readers\n",
    "from pyresample import create_area_def\n",
    "from satpy.writers import get_enhanced_image\n",
    "from datetime import datetime\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from glob import glob\n",
    "import cartopy.crs as ccrs\n",
    "import cartopy.feature as cfeature\n",
    "from satpy import MultiScene\n",
    "from satpy.multiscene import timeseries\n",
    "\n",
    "def FLBayfigure(monthyear):\n",
    "    \n",
    "    i=0\n",
    "    base = '/home/hboi-ouri/Projects/RS_Files/FLBayDailies/' + monthyear + '/MYD021KM.'\n",
    "\n",
    "    #files to be used\n",
    "    filenames = glob('/home/hboi-ouri/Projects/RS_Files/FLBayDailies/' + monthyear + '/MYD021KM.*')\n",
    "    swats = np.unique([f.split('.')[1] for f in filenames])\n",
    "    \n",
    "\n",
    "    #area in the figure\n",
    "    extent = [-82.0, 24.4, -80.0, 25.6]\n",
    "    my_area = create_area_def('my_area', {'proj': 'lcc', 'lon_0': -81.0, 'lat_0': 25.0, 'lat_1': 25.0, 'lat_2': 25.0},\n",
    "                    width=1500, height=750,\n",
    "                    area_extent=extent, units='degrees')\n",
    "        \n",
    "    fig =  plt.figure(figsize=(6, 4), dpi=400)\n",
    "\n",
    "    #loop\n",
    "    for swat in swats:\n",
    "        dayfiles = glob(base+swat+'*')\n",
    "        scn = Scene(dayfiles, reader='modis_l1b')\n",
    "        scn.load(['true_color'])\n",
    "\n",
    "        #reproject\n",
    "        new_scn = scn.resample(my_area)\n",
    "\n",
    "        #generate RGB from true color\n",
    "        rgb = get_enhanced_image(new_scn['true_color'])\n",
    "\n",
    "        #extract projection and lon lat from products\n",
    "        crs = new_scn['true_color'].attrs['area'].to_cartopy_crs()\n",
    "        lons, lats = new_scn['true_color'].attrs['area'].get_lonlats()\n",
    "\n",
    "        #left true color\n",
    "        ax1 = plt.subplot(projection=crs)\n",
    "        rgb.data.plot.imshow(rgb='bands', transform=crs, ax=ax1)\n",
    "\n",
    "        #title & save\n",
    "        ax1.set_title('MODISA_FLBay_%s' % new_scn.start_time.isoformat())\n",
    "        fig.savefig('/home/hboi-ouri/Projects/NASA_Project/outputs/DailyImages/FLBay/FLBay%s_rgb.png' % new_scn.start_time.isoformat())\n",
    "        fig.clear()\n",
    "        \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "bf85f2e4",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n",
      "Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/geotiepoints/geointerpolator.py:89: RuntimeWarning: invalid value encountered in arccos\n",
      "  lat_z_only = 90 - np.rad2deg(np.arccos(z__ / radius))\n",
      "/home/hboi-ouri/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/modifiers/angles.py:502: RuntimeWarning: invalid value encountered in log\n",
      "  grad_factor = 1. - np.log(grad_factor + 1) / np.log(2)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<Figure size 2400x1600 with 0 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": [
       "<Figure size 2400x1600 with 0 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": [
       "<Figure size 2400x1600 with 0 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "FLBayfigure('July2022')\n",
    "FLBayfigure('August2022')\n",
    "FLBayfigure('September2022')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "20e0af33",
   "metadata": {},
   "outputs": [],
   "source": [
    "from satpy import Scene, find_files_and_readers\n",
    "from pyresample import create_area_def\n",
    "from satpy.writers import get_enhanced_image\n",
    "from datetime import datetime\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from glob import glob\n",
    "import cartopy.crs as ccrs\n",
    "import cartopy.feature as cfeature\n",
    "from satpy import MultiScene\n",
    "from satpy.multiscene import timeseries\n",
    "\n",
    "def TXLAfigure(monthyear):\n",
    "    \n",
    "    i=0\n",
    "    base = '/home/hboi-ouri/Projects/RS_Files/TXLADailies/' + monthyear + '/MYD021KM.'\n",
    "\n",
    "    filenames = glob('/home/hboi-ouri/Projects/RS_Files/TXLADailies/' + monthyear + '/MYD021KM.*')\n",
    "    swats = np.unique([f.split('.')[1] for f in filenames])\n",
    "    \n",
    "    extent = [-94, 27.5, -88, 30.5]\n",
    "    my_area = create_area_def('my_area', {'proj': 'lcc', 'lon_0': -91., 'lat_0': 29.5, 'lat_1': 29.5, 'lat_2': 29.5},\n",
    "                width=1500, height=750,\n",
    "                area_extent=extent, units='degrees')    \n",
    "        \n",
    "    fig =  plt.figure(figsize=(6, 4), dpi=400)\n",
    "\n",
    "    for swat in swats:\n",
    "        dayfiles = glob(base+swat+'*')\n",
    "        scn = Scene(dayfiles, reader='modis_l1b')\n",
    "        scn.load(['true_color'])\n",
    "\n",
    "        new_scn = scn.resample(my_area)\n",
    "\n",
    "        rgb = get_enhanced_image(new_scn['true_color'])\n",
    "\n",
    "        crs = new_scn['true_color'].attrs['area'].to_cartopy_crs()\n",
    "        lons, lats = new_scn['true_color'].attrs['area'].get_lonlats()\n",
    "\n",
    "        ax1 = plt.subplot(projection=crs)\n",
    "        rgb.data.plot.imshow(rgb='bands', transform=crs, ax=ax1)\n",
    "        \n",
    "        ax1.set_title('MODISA_Mdelta_%s' % new_scn.start_time.isoformat())\n",
    "        fig.savefig('/home/hboi-ouri/Projects/NASA_Project/outputs/DailyImages/TXLA/MODISA_Mdelta_%s_rgb.png' % new_scn.start_time.isoformat())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "945624d3",
   "metadata": {},
   "outputs": [],
   "source": [
    "from satpy import Scene, find_files_and_readers\n",
    "from pyresample import create_area_def\n",
    "from satpy.writers import get_enhanced_image\n",
    "from datetime import datetime\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from glob import glob\n",
    "import cartopy.crs as ccrs\n",
    "import cartopy.feature as cfeature\n",
    "from satpy import MultiScene\n",
    "from satpy.multiscene import timeseries\n",
    "\n",
    "def combinedplot():\n",
    "\n",
    "    base = '/home/hboi-ouri/Projects/NASA_Project/outputs/CombinedNC/MODIS/'\n",
    "    \n",
    "    filenames = glob('/home/hboi-ouri/Projects/NASA_Project/outputs/CombinedNC/MODIS/*')\n",
    "\n",
    "    \n",
    "    extent = [-94, 27.5, -88, 30.5]\n",
    "    my_area = create_area_def('my_area', {'proj': 'lcc', 'lon_0': -91., 'lat_0': 29.5, 'lat_1': 29.5, 'lat_2': 29.5},\n",
    "                width=1500, height=750,\n",
    "                area_extent=extent, units='degrees')    \n",
    "        \n",
    "    fig =  plt.figure(figsize=(6, 4), dpi=400)\n",
    "\n",
    "    for file in filenames:\n",
    "        dayfiles = glob(base+'*')\n",
    "        scn = Scene(dayfiles, reader='modis_l1b')\n",
    "        scn.load(['true_color'])\n",
    "\n",
    "        new_scn = scn.resample(my_area)\n",
    "\n",
    "        rgb = get_enhanced_image(new_scn['true_color'])\n",
    "\n",
    "        crs = new_scn['true_color'].attrs['area'].to_cartopy_crs()\n",
    "        lons, lats = new_scn['true_color'].attrs['area'].get_lonlats()\n",
    "\n",
    "        ax1 = plt.subplot(projection=crs)\n",
    "        rgb.data.plot.imshow(rgb='bands', transform=crs, ax=ax1)\n",
    "        \n",
    "        date = [f.split('.')[1] for f in files]\n",
    "        year = ((date[1])[0:4])\n",
    "        month = ((date[1])[4:6])\n",
    "        \n",
    "        ax1.set_title('MODISA_Mdelta_Combined_' + year + '_' + month)\n",
    "        fig.savefig('/home/hboi-ouri/Projects/NASA_Project/outputs/CombinedNC/MODISFigures/CombinedMODISA' + year + '_' + month + '.png')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "e3714946",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "No filenames found for reader: modis_l1b\n",
      "Don't know how to open the following files: {'/home/hboi-ouri/Projects/NASA_Project/outputs/CombinedNC/MODIS/2010_08_MODIS_L2.nc', '/home/hboi-ouri/Projects/NASA_Project/outputs/CombinedNC/MODIS/2012_09_MODIS_L2.nc', '/home/hboi-ouri/Projects/NASA_Project/outputs/CombinedNC/MODIS/2010_07_MODIS_L2.nc'}\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "No supported files found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Input \u001b[0;32mIn [15]\u001b[0m, in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43mcombinedplot\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "Input \u001b[0;32mIn [14]\u001b[0m, in \u001b[0;36mcombinedplot\u001b[0;34m()\u001b[0m\n\u001b[1;32m     27\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m file \u001b[38;5;129;01min\u001b[39;00m filenames:\n\u001b[1;32m     28\u001b[0m     dayfiles \u001b[38;5;241m=\u001b[39m glob(base\u001b[38;5;241m+\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m*\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m---> 29\u001b[0m     scn \u001b[38;5;241m=\u001b[39m \u001b[43mScene\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdayfiles\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mreader\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mmodis_l1b\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[1;32m     30\u001b[0m     scn\u001b[38;5;241m.\u001b[39mload([\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mtrue_color\u001b[39m\u001b[38;5;124m'\u001b[39m])\n\u001b[1;32m     32\u001b[0m     new_scn \u001b[38;5;241m=\u001b[39m scn\u001b[38;5;241m.\u001b[39mresample(my_area)\n",
      "File \u001b[0;32m~/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/scene.py:133\u001b[0m, in \u001b[0;36mScene.__init__\u001b[0;34m(self, filenames, reader, filter_parameters, reader_kwargs)\u001b[0m\n\u001b[1;32m    130\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m filenames:\n\u001b[1;32m    131\u001b[0m     filenames \u001b[38;5;241m=\u001b[39m convert_remote_files_to_fsspec(filenames, storage_options)\n\u001b[0;32m--> 133\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_readers \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_create_reader_instances\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfilenames\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mfilenames\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    134\u001b[0m \u001b[43m                                              \u001b[49m\u001b[43mreader\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mreader\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    135\u001b[0m \u001b[43m                                              \u001b[49m\u001b[43mreader_kwargs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcleaned_reader_kwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    136\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_datasets \u001b[38;5;241m=\u001b[39m DatasetDict()\n\u001b[1;32m    137\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_wishlist \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mset\u001b[39m()\n",
      "File \u001b[0;32m~/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/scene.py:154\u001b[0m, in \u001b[0;36mScene._create_reader_instances\u001b[0;34m(self, filenames, reader, reader_kwargs)\u001b[0m\n\u001b[1;32m    149\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_create_reader_instances\u001b[39m(\u001b[38;5;28mself\u001b[39m,\n\u001b[1;32m    150\u001b[0m                              filenames\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[1;32m    151\u001b[0m                              reader\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[1;32m    152\u001b[0m                              reader_kwargs\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m):\n\u001b[1;32m    153\u001b[0m     \u001b[38;5;124;03m\"\"\"Find readers and return their instances.\"\"\"\u001b[39;00m\n\u001b[0;32m--> 154\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mload_readers\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfilenames\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mfilenames\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    155\u001b[0m \u001b[43m                        \u001b[49m\u001b[43mreader\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mreader\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    156\u001b[0m \u001b[43m                        \u001b[49m\u001b[43mreader_kwargs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mreader_kwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/readers/__init__.py:581\u001b[0m, in \u001b[0;36mload_readers\u001b[0;34m(filenames, reader, reader_kwargs)\u001b[0m\n\u001b[1;32m    578\u001b[0m         \u001b[38;5;28;01mbreak\u001b[39;00m\n\u001b[1;32m    580\u001b[0m _check_remaining_files(remaining_filenames)\n\u001b[0;32m--> 581\u001b[0m \u001b[43m_check_reader_instances\u001b[49m\u001b[43m(\u001b[49m\u001b[43mreader_instances\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    582\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m reader_instances\n",
      "File \u001b[0;32m~/miniconda3/envs/Satpy/lib/python3.8/site-packages/satpy/readers/__init__.py:620\u001b[0m, in \u001b[0;36m_check_reader_instances\u001b[0;34m(reader_instances)\u001b[0m\n\u001b[1;32m    618\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_check_reader_instances\u001b[39m(reader_instances):\n\u001b[1;32m    619\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m reader_instances:\n\u001b[0;32m--> 620\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mNo supported files found\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m    621\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28many\u001b[39m(\u001b[38;5;28mlist\u001b[39m(r\u001b[38;5;241m.\u001b[39mavailable_dataset_ids) \u001b[38;5;28;01mfor\u001b[39;00m r \u001b[38;5;129;01min\u001b[39;00m reader_instances\u001b[38;5;241m.\u001b[39mvalues()):\n\u001b[1;32m    622\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mNo dataset could be loaded. Either missing \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    623\u001b[0m                          \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mrequirements (such as Epilog, Prolog) or none of the \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    624\u001b[0m                          \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mprovided files match the filter parameters.\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[0;31mValueError\u001b[0m: No supported files found"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<Figure size 2400x1600 with 0 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "combinedplot()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fe8d6113",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
